#!/bin/sh
#	Installs the JSONL text filters into BBEdit's Text Filters folder as
#	small wrappers. BBEdit runs filters with a minimal PATH (no node, no
#	homebrew), and the filter scripts locate the repo CLI relative to their
#	own location — so plain copies break. Each wrapper fixes PATH and
#	delegates to the script inside this repository, so installed filters
#	always track the current code.
set -eu

DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
FILTERS_SRC="$DIR/filters"
FILTERS_DEST="$HOME/Library/Application Support/BBEdit/Text Filters"

#	stable locations BBEdit's environment won't have; node must be in one
EXTRA_PATH="/opt/homebrew/bin:/usr/local/bin"

if ! PATH="$EXTRA_PATH" command -v node >/dev/null 2>&1; then
  echo "error: no 'node' in $EXTRA_PATH." >&2
  echo "Install Node.js via Homebrew, or edit EXTRA_PATH in this script." >&2
  exit 1
fi

mkdir -p "$FILTERS_DEST"

for src in "$FILTERS_SRC"/*.sh; do
  name=$(basename "$src")
  dest="$FILTERS_DEST/$name"

  cat > "$dest" <<EOF
#!/bin/sh
#	Generated by install-filters.sh — do not edit; re-run the installer
#	from the jsonl-tools repository instead.
export PATH="$EXTRA_PATH:\$PATH"
exec "$src"
EOF

  chmod +x "$dest"
  echo "installed: $name"
done

echo "done: filters appear under BBEdit's Text > Apply Text Filter menu"
